################################################################################################
#  Copyright (c) Rowe Wilson Frederisk Holme. All rights reserved.
#  Licensed under the MIT License. See License.txt in the project root for license information.
################################################################################################

---
name: "MarketsPublish"

on:
  # Start action after created a release
  # release:
  #   types:
  #     - created
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: |
          npm install -g yarn vsce ovsx
          yarn install

      - name: Test
        run: xvfb-run -a yarn test

      - name: Publish to VSCE
        if: ${{ success() }}
        run: vsce publish --yarn
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to OVSX
        if: ${{ success() }}
        run: ovsx publish --yarn
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
